### PR TITLE
Change method signatures to mirror SDK interface

### LINKED ISSUE #3: Calling alvariumAnnotate() with the checksum annotator only causes additional empty annotator list to be published by the SDK
### Steps to reproduce

1. Create an empty file at `./checksum`
2. Run `mosquitto_sub -t alvarium-test-topic`
3.  Run/call `alvariumAnnotate(['checksum'], './checksum')` from a jenkins instance
4. Inspect the stdout from the process running in (2)
5. Base64decode the content from the 2 payloads, the second one will be an empty annotator list

### PR DESCRIPTION
**Pull request by Ali-Amin**
Fix #3 

* Replace the `alvariumAnnotate()` method with `alvariumCreate()`, `alvariumMutate()` and `alvariumTransit()`
* Handle a null `artifactPath` when a 'checksum' annotator is called
* Update README.md

### CODE REVIEW

**Review by o-eissa — COMMENTED** [review]
I've been searching for ways to test shared libraries [ex](https://pushbuildtestdeploy.com/unit-testing-for-jenkins-shared-libraries/), but it seems it would need restructuring the whole project. For now, I went with a static review while I'm trying to run an instance that I can manually test on.
And if that testability change deemed necessary, we can create an issue for it.

File: vars/alvariumCreate.groovy [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import com.alvarium.DefaultSdk;
+import com.alvarium.Sdk;
+import com.alvarium.SdkInfo;
+
+import com.alvarium.annotators.Annotator;
+import com.alvarium.utils.PropertyBag;
+
+def call(List<String> annotatorKinds, String artifactPath=null) {
+
+    if (annotatorKinds.contains('checksum')) {
```
Comment (o-eissa) [inline vars/alvariumCreate.groovy]: Is it better to have these nested ifs &&ed instead or is it meant to separate the concerns or extension later?

**Review by o-eissa — COMMENTED** [review]
As I said that's static reviewing only till I can run an instance to try on or figure a way to make it "unit testable". I think up to you if you think it'd need to wait for that but otherwise LGTM.

**Comment by o-eissa** [comment]
Also, I got the idea of @NonCPS but maybe not quite well. For example, why couldn't we use it for getAnnotatorConfig since it's relatively simple and doesn't call any methods in CPS mode?

File: vars/alvariumCreate.groovy [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+        sdkInfo,
+        logger    
+    )
+
+    DefaultSdk sdk = new DefaultSdk(annotators, sdkInfo, logger)
+    sdk.create(ctx, pipelineId.getBytes())
+    sdk.close()
+}
+
+@NonCPS
```
Comment (o-eissa) [inline vars/alvariumCreate.groovy:48]: Also, I got the idea of @NonCPS but maybe not quite well. For example, why couldn't we use it for getAnnotatorConfig since it's relatively simple and doesn't call any methods in CPS mode?

File: vars/alvariumGetAnnotators.groovy [hunk 3]
```diff
@@ -58,17 +45,9 @@ def call(List<String> annotatorKinds, String artifactPath=null) {
                     artifactPath,
                     checksum.getAbsolutePath()
                 )
```
Comment (o-eissa) [inline vars/alvariumGetAnnotators.groovy:47]: Is the File object needed?
Can we pass the path directly as the source-code case?

**Comment by o-eissa** [comment]
```java
            case "checksum":
                File artifact = new File(artifactPath);
                File checksum = new File(
                    "${JENKINS_HOME}/jobs/${JOB_NAME}/${BUILD_NUMBER}/${artifact.getName()}.checksum"
                )
                ChecksumAnnotatorProps props = new ChecksumAnnotatorProps(
                    artifactPath,
                    checksum.getAbsolutePath()
                )
```
May be irrelevant to that PR changes but do we need the File objects, can't we pass the string paths directly in the props as the source-code case?

**Review by o-eissa — COMMENTED** [review]
```alvariumGetAnnotators.groovy```
```java
            case "checksum":
                File artifact = new File(artifactPath);
                File checksum = new File(
                    "${JENKINS_HOME}/jobs/${JOB_NAME}/${BUILD_NUMBER}/${artifact.getName()}.checksum"
                )
                ChecksumAnnotatorProps props = new ChecksumAnnotatorProps(
                    artifactPath,
                    checksum.getAbsolutePath()
                )
```
May be irrelevant to that PR changes but do we need the File objects, can't we pass the string paths directly in the props as the source-code case?

File: vars/alvariumCreate.groovy (hunk 2 above)
Comment (Ali-Amin) [reply vars/alvariumCreate.groovy:48]: I have mainly used the `@NonCPS` decorator to tell Jenkins that this block of code contains objects that are non-serializable (I believe this not to be true, but for some reason the Jenkins groovy toolbox does not recognize this). 

The side-effect of this is when the pipeline stops for whatever reason, jenkins will not be able to save the state of objects used inside the method, which will probably result in saving the state before the method runs, similar to a transaction. This side-effect is fine for our use-case I believe.

**Comment by Ali-Amin** [comment]
> `alvariumGetAnnotators.groovy`
> 
> ```java
>             case "checksum":
>                 File artifact = new File(artifactPath);
>                 File checksum = new File(
>                     "${JENKINS_HOME}/jobs/${JOB_NAME}/${BUILD_NUMBER}/${artifact.getName()}.checksum"
>                 )
>                 ChecksumAnnotatorProps props = new ChecksumAnnotatorProps(
>                     artifactPath,
>                     checksum.getAbsolutePath()
>                 )
> ```
> 
> May be irrelevant to that PR changes but do we need the File objects, can't we pass the string paths directly in the props as the source-code case?

I used `File` as a way to store meta information on the checksum for convenience... I guess some alternatives are fine as well. Do you have some reason as to why `File` might not be the best approach ?

File: vars/alvariumCreate.groovy (hunk 1 above)
Comment (Ali-Amin) [reply vars/alvariumCreate.groovy]: Resolved in df288382f27c3141e336464753bceb0646c948c6.

Comment (o-eissa) [reply vars/alvariumCreate.groovy]: I think I have the access and I can do the edits from my side but wanted to ensure if it has a certain purpose also in alvariumTransit and alvariumMutate.

**Comment by o-eissa** [comment]
> > `alvariumGetAnnotators.groovy`
> > ```java
> >             case "checksum":
> >                 File artifact = new File(artifactPath);
> >                 File checksum = new File(
> >                     "${JENKINS_HOME}/jobs/${JOB_NAME}/${BUILD_NUMBER}/${artifact.getName()}.checksum"
> >                 )
> >                 ChecksumAnnotatorProps props = new ChecksumAnnotatorProps(
> >                     artifactPath,
> >                     checksum.getAbsolutePath()
> >                 )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > May be irrelevant to that PR changes but do we need the File objects, can't we pass the string paths directly in the props as the source-code case?
> 
> I used `File` as a way to store meta information on the checksum for convenience... I guess some alternatives are fine as well. Do you have some reason as to why `File` might not be the best approach ?

I meant if we should store it in the File object if it's not used now and we only need the file path. But didn't catch it's used in ```artifact.getName()``` to get the file name itself instead of the full path. It may be more convenient as you said and better for extension later.

File: vars/alvariumCreate.groovy (hunk 1 above)
Comment (Ali-Amin) [reply vars/alvariumCreate.groovy]: aha I missed that :D

Comment (Ali-Amin) [reply vars/alvariumCreate.groovy]: Resolved in d879b6ed10db562b6478f848bfdb2f23bb2bf8e4
